[package]
name = "straft"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
slog = "2.7.0"
slog-stdlog = "4.1.1"

[build-dependencies]
tonic-build = "0.8"
